### ISSUE TITLE
Live search

### ISSUE THREAD

**Issue by whatterz** [ministryofjustice/moj-design-system-backlog#27]
**Service**: Claim for Crown court defence
**Phase**: Live
**Department**: Legal Aid Agency

![laa_cccd_live_search_offences](https://user-images.githubusercontent.com/23444/51529321-57188900-1e30-11e9-8d97-7bad96985c5d.gif)

**Comment by SimonCM** [comment]
Service: Apply for legal aid 
Phase: Private beta (Currently being built)
Department: Legal Aid Agency

![apply-legal-aid-search-select](https://user-images.githubusercontent.com/6673701/51745587-3738cd80-209b-11e9-90d7-6cb2a95bfcb4.gif)

![error_proceedings 1](https://user-images.githubusercontent.com/6673701/51742917-fd63c900-2092-11e9-83c7-19ea6482641c.png)

**Comment by adamsilver** [comment]
Can we describe the need for this over and above a standard search with a page refresh?

**Comment by adamsilver** [comment]
Marked as not doing because:

1. It only works with JS—we could encourage a solution that works without as per current DS guidance
2. It mimics native behaviour
3. It only searches what’s on the page and...
4. What’s on the page should only be a small number of items (for performance/usability) right unless we exposed a load all things feature
